HW1 is competed
azicussdu/otus_homework pull request #1
Opened 2024-08-06 06:04 UTC by azicussdu

## Домашнее задание №1 «Hello, OTUS!»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Используется `stringutil` - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-06 07:31 UTC, vladislavmass requested changes

2024-08-06 07:31 UTC, vladislavmass commented on hw01_hello_otus/go.mod
> +module github.com/azicussdu/otus_homework
Неверное имя модуля. Правильное имя модуля в данном случае `github.com/azicussdu/otus_homework/hw01_hello_otus`

2024-08-07 11:56 UTC, azicussdu commented on hw01_hello_otus/go.mod
> +module github.com/azicussdu/otus_homework
Исправил. Спасибо @vladislavmass

2024-08-08 08:02 UTC, vladislavmass approved these changes

2024-08-10 11:33 UTC, merged