Hw02 unpack string
azicussdu/otus_homework pull request #2
Opened 2024-08-12 10:27 UTC by azicussdu

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-12 14:22 UTC, vladislavmass requested changes

2024-08-12 14:22 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			lastChar = string(builder.String()[builder.Len()-1])
Таким образом в `lastChar` попадет не последний символ, а последний байт. И это будет работать с символами кодировки  ASCII так как любой ее символ это 1 байт, но не будет работать с многобайтовыми символами. Для проверки этого можно использовать следующий тесткейс `	{input: "dabcф2", expected: "dabcфф"},`

2024-08-12 14:22 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		case unicode.IsLetter(chr) || chr == '\n':
Откуда взялось правило про литеру? Код должен распаковывать и точки и прочие символы, а также обрабатывать все управляющие символы такие как `\t`. Тоесть тест кейс должен нормально отрабатывать следующий тест кейс `{input: "aa.0b", expected: "aab"},`

2024-08-12 14:22 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
Этот механизм работает несвсем корректно. Этот тест кейс должен выдавать ошибку но он выдает очень интересную строку ``` `qwe\.5` ```

2024-08-13 05:07 UTC, azicussdu commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
А какой был input если output: `qwe\.5` ?

2024-08-13 05:09 UTC, azicussdu commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
Попробую все исправить, честно сказать я не думал что будут такие разные тест кейсы. Думал упражнение только чтобы привыкнуть к Голанг и главное чтобы только отрабатывал данные нам в задаче тесты. Буду править тогда.

2024-08-13 05:12 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
В данном случае это и есть input, который работает не верно

2024-08-13 05:16 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
Это все такие курс профессионал, поэтому тут сразу в бой что говорится. Но если будут сложность, то можно решить только задание без звездочки. Задание со звездочкой на бал никак не влияет

2024-08-13 05:39 UTC, azicussdu commented on hw02_unpack_string/unpack.go
> +		case chr == '\\':
Исправил все замечания.

2024-08-13 05:48 UTC, vladislavmass commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\.5`, expected: `qwe.....`},
Данный тест кейс должен приводит к ошибке. Так как экранизировать можно только / или цифру

2024-08-13 06:35 UTC, vladislavmass requested changes
Работа стала лучше. Но не вижу правок по файлу go.mod, а также некорректно работает тест кейс 
```
`qwe\`
```
Этот тест кейс должен приводить к ошибке. Так как последний слэш ничего не экранизирует. 
После этого необходимо повторно сдать дз на проверку через чат

2024-08-13 08:12 UTC, vladislavmass approved these changes

2024-08-19 08:18 UTC, merged