HW4 first commit
azicussdu/otus_homework pull request #4
Opened 2024-09-04 10:34 UTC by azicussdu

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-04 16:00 UTC, hungry-honeybadger requested changes

2024-09-04 16:00 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if l.len > 0 {
Зачем сдвигать все в право из за одного условия. Ведь можно сделать проще 
```
if  l.len==0{
    return
}
```

2024-09-04 16:00 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if l.len > 0 && l.front != i {
Зачем сдвигать все в право из за одного условия. Ведь можно сделать проще 
```
if l.len==0 ||  l.front == i{
    return
}
```

2024-09-04 16:00 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	if l.queue.Len() > l.capacity {
Капасити это размер который не должен быть превышен, а тут получается так что хоть и не на долго но идет превышение. Правильные подход сначала чистим, потом добавляем

2024-09-04 16:00 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	l.items = map[Key]*ListItem{}
Лучше выделить сразу места в мапе через make

2024-09-05 05:06 UTC, azicussdu commented on hw04_lru_cache/cache.go
> +	l.items = map[Key]*ListItem{}
Исправлю. Но я так понял практически они не отличаются логикой? Или есть разница?

2024-09-05 06:15 UTC, vladislavmass approved these changes

2024-09-05 14:05 UTC, merged